autoInstallPeers: true
nodeLinker: hoisted
minimumReleaseAgeExclude:
  - '@deepseek-ai/*'
  - dsh-mnemon-source-runtime@0.5.9
  - dsh-mnemon-strategy-default-three-tier@0.5.6
  - dsh-mnemon@0.5.15
packages:
  - .
  - packages/dsh-tavern-remote
